# Generated by Django 5.1.5 on 2025-02-18 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_address_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='app1.seller'),
        ),
    ]
